### ISSUE TITLE
support lombok annotations with sonar-java plugin

### ISSUE THREAD

**Issue by zdhamasha** [codeclimate/codeclimate-sonar-java#63]
the following is the .codeclimate.yml file content 

```


version: "2"
plugins:
  csslint:
    enabled: false
  structure:
    enabled: true
  sonar-java:
    enabled: true
    config:
        sonar.java.source: "8"
  coffeelint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
        - ruby
        - javascript
        - python
        - php
  eslint:
    enabled: false
    channel: "stable"
  fixme:
    enabled: true
  rubocop:
    enabled: false
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/__tests__/"
  - "**/__mocks__/" 
```

after applying the sonar-java engine ends, report to us 

 **Major - Add a private constructor to hide the implicit public one.** 

```
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class PageMapper {

    }
}
```
why the sonar-java  does not support recognize the lombok annotations
